/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.oficina.project.view.TelaPrincipal.CadastrarAdmView;

import com.oficina.project.controller.Administradores.BuscarAdmController;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ComboBoxEditor;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Venicio
 */
public class CadastrarAdmView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarAdmView
     */
    public CadastrarAdmView() {
        initComponents();
        new com.oficina.project.controller.Administradores.CadastrarAdmController(this);
        new com.oficina.project.controller.Administradores.BuscarAdmController(this);
        new com.oficina.project.controller.Administradores.ApagarAdmController(this);
        new com.oficina.project.controller.Administradores.EditarAdmController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        CampoNome = new javax.swing.JTextField();
        CampoTelefone = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        CampoSenha = new javax.swing.JTextField();
        LbNome = new javax.swing.JLabel();
        LbEmail = new javax.swing.JLabel();
        LbTelefone = new javax.swing.JLabel();
        Lbcargo = new javax.swing.JLabel();
        ComboBoxCargo = new javax.swing.JComboBox<>();
        InternaEditarUsuario = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaUsuarios = new javax.swing.JTable();
        CampoPesquisar = new javax.swing.JTextField();
        InternaDadosPesquisa = new javax.swing.JInternalFrame();
        LbInfoEmail = new javax.swing.JLabel();
        LbInfoNome1 = new javax.swing.JLabel();
        LbInfoSenha = new javax.swing.JLabel();
        LbInfotelefone = new javax.swing.JLabel();
        LbInfoCargo = new javax.swing.JLabel();
        LbInfoDataCadastro = new javax.swing.JLabel();
        LbInfoDataAtualizacao = new javax.swing.JLabel();
        CampoInfoDataAtualizacao = new javax.swing.JTextField();
        CampoInfoDataCadastro = new javax.swing.JTextField();
        CampoInfoNome = new javax.swing.JTextField();
        CampoInfoEmail = new javax.swing.JTextField();
        CampoInfoSenha = new javax.swing.JTextField();
        CampoInfoTelefone = new javax.swing.JTextField();
        CampoInfoCargo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LbInfoNome2 = new javax.swing.JLabel();
        CampoInfoId = new javax.swing.JTextField();
        BtEditar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        IconPesquisar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtSalvar = new javax.swing.JButton();
        InternaStatus = new javax.swing.JInternalFrame();
        BarraProgresso = new javax.swing.JProgressBar();
        LbResultado = new javax.swing.JLabel();
        LbNome1 = new javax.swing.JLabel();
        LbEmail1 = new javax.swing.JLabel();
        LbSenha = new javax.swing.JLabel();
        LbTelefone1 = new javax.swing.JLabel();
        Lbcargo1 = new javax.swing.JLabel();
        LbResultadoNome = new javax.swing.JLabel();
        LbResultadoSenha = new javax.swing.JLabel();
        LbResultadoEmail = new javax.swing.JLabel();
        LbResultadoCargo = new javax.swing.JLabel();
        LbResultadoTelefone = new javax.swing.JLabel();
        Lbcargo2 = new javax.swing.JLabel();
        LbResultadoData = new javax.swing.JLabel();
        LbSenha1 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "    Cadastrar Funcionario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        CampoNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CampoTelefone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CampoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefoneActionPerformed(evt);
            }
        });

        CampoEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CampoSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LbNome.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbNome.setText("Nome:");

        LbEmail.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbEmail.setText("Email:");

        LbTelefone.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbTelefone.setText("Telefone:");

        Lbcargo.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        Lbcargo.setText("Cargo:");

        ComboBoxCargo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario,", "Administrador,", "Cliente" }));
        ComboBoxCargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ComboBoxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCargoActionPerformed(evt);
            }
        });

        InternaEditarUsuario.setBackground(new java.awt.Color(183, 183, 167));
        InternaEditarUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14))); // NOI18N
        InternaEditarUsuario.setVisible(true);

        TabelaUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        TabelaUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelaUsuarios.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        TabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nome", "Login", "Senha", "Telefone", "Cargo", "Data_cadastro", "Data_Atualizacação"
            }
        ));
        TabelaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaUsuarios);

        CampoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisarActionPerformed(evt);
            }
        });

        InternaDadosPesquisa.setBackground(new java.awt.Color(153, 153, 153));
        InternaDadosPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informações de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        InternaDadosPesquisa.setForeground(new java.awt.Color(204, 204, 204));
        InternaDadosPesquisa.setVisible(true);

        LbInfoEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoEmail.setText("Email:");

        LbInfoNome1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoNome1.setText("Nome:");

        LbInfoSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoSenha.setText("Senha");

        LbInfotelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfotelefone.setText("Telefone:");

        LbInfoCargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoCargo.setText("Cargo");

        LbInfoDataCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoDataCadastro.setText("Data de Cadastro:");

        LbInfoDataAtualizacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoDataAtualizacao.setText("Data de Atualização:");

        CampoInfoCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoInfoCargoActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/usuario-final (1).png"))); // NOI18N

        LbInfoNome2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbInfoNome2.setText("ID:");

        javax.swing.GroupLayout InternaDadosPesquisaLayout = new javax.swing.GroupLayout(InternaDadosPesquisa.getContentPane());
        InternaDadosPesquisa.getContentPane().setLayout(InternaDadosPesquisaLayout);
        InternaDadosPesquisaLayout.setHorizontalGroup(
            InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbInfoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbInfoNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbInfoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CampoInfoNome)
                                    .addComponent(CampoInfoEmail)
                                    .addComponent(CampoInfoSenha)))
                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbInfotelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbInfoCargo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CampoInfoTelefone)
                                    .addComponent(CampoInfoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbInfoNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(jLabel4)
                        .addGap(80, 80, 80))
                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbInfoDataAtualizacao)
                            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(LbInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoInfoDataAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(206, 206, 206))))
        );
        InternaDadosPesquisaLayout.setVerticalGroup(
            InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InternaDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbInfoNome1)
                            .addComponent(CampoInfoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbInfoNome2)
                            .addComponent(CampoInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbInfoEmail)
                            .addComponent(CampoInfoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbInfoSenha)
                            .addComponent(CampoInfoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoInfoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbInfotelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbInfoCargo)
                            .addComponent(CampoInfoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoDataCadastro)
                    .addComponent(CampoInfoDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInfoDataAtualizacao)
                    .addComponent(CampoInfoDataAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });

        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        IconPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lupa.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Editar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Excluir");

        javax.swing.GroupLayout InternaEditarUsuarioLayout = new javax.swing.GroupLayout(InternaEditarUsuario.getContentPane());
        InternaEditarUsuario.getContentPane().setLayout(InternaEditarUsuarioLayout);
        InternaEditarUsuarioLayout.setHorizontalGroup(
            InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                .addComponent(IconPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoPesquisar))
                            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel1)
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel2))
                                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(BtEditar)
                                        .addGap(48, 48, 48)
                                        .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 217, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InternaDadosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        InternaEditarUsuarioLayout.setVerticalGroup(
            InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(InternaDadosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InternaEditarUsuarioLayout.createSequentialGroup()
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconPesquisar))
                        .addGap(38, 38, 38)
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtEditar)
                            .addComponent(BtExcluir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternaEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtSalvar.setText("Cadastrar Usuario");
        BtSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        InternaStatus.setBackground(new java.awt.Color(102, 102, 102));
        InternaStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        InternaStatus.setVisible(true);

        BarraProgresso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BarraProgresso.setForeground(new java.awt.Color(204, 0, 0));
        BarraProgresso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Progresso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        BarraProgresso.setStringPainted(true);

        LbResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LbResultado.setText("Resultado:");

        LbNome1.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbNome1.setText("Nome:");

        LbEmail1.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbEmail1.setText("Email:");

        LbSenha.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbSenha.setText("Senha:");

        LbTelefone1.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbTelefone1.setText("Telefone:");

        Lbcargo1.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        Lbcargo1.setText("Cargo:");

        LbResultadoNome.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        LbResultadoSenha.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        LbResultadoEmail.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        LbResultadoCargo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        LbResultadoTelefone.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        Lbcargo2.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        Lbcargo2.setText("Cadastrado em:");

        LbResultadoData.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N

        javax.swing.GroupLayout InternaStatusLayout = new javax.swing.GroupLayout(InternaStatus.getContentPane());
        InternaStatus.getContentPane().setLayout(InternaStatusLayout);
        InternaStatusLayout.setHorizontalGroup(
            InternaStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaStatusLayout.createSequentialGroup()
                .addGroup(InternaStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternaStatusLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BarraProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(InternaStatusLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(LbResultado))
                    .addGroup(InternaStatusLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(InternaStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InternaStatusLayout.createSequentialGroup()
                                .addComponent(LbSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbResultadoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InternaStatusLayout.createSequentialGroup()
                                .addComponent(Lbcargo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LbResultadoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InternaStatusLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(InternaStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InternaStatusLayout.createSequentialGroup()
                                        .addComponent(LbEmail1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LbResultadoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(InternaStatusLayout.createSequentialGroup()
                                        .addComponent(LbNome1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LbResultadoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(InternaStatusLayout.createSequentialGroup()
                                .addComponent(LbTelefone1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbResultadoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InternaStatusLayout.createSequentialGroup()
                                .addComponent(Lbcargo2)
                                .addGap(18, 18, 18)
                                .addComponent(LbResultadoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        InternaStatusLayout.setVerticalGroup(
            InternaStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternaStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BarraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbResultado)
                .addGap(18, 18, 18)
                .addGroup(InternaStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNome1)
                    .addComponent(LbResultadoNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEmail1)
                    .addComponent(LbResultadoEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbSenha)
                    .addComponent(LbResultadoSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbTelefone1)
                    .addComponent(LbResultadoTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbcargo1)
                    .addComponent(LbResultadoCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InternaStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbcargo2)
                    .addComponent(LbResultadoData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LbSenha1.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        LbSenha1.setText("Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(LbSenha1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbEmail)
                                    .addComponent(LbNome)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Lbcargo)
                                .addComponent(LbTelefone)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CampoSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CampoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(ComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(InternaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InternaEditarUsuario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNome)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEmail)
                    .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbSenha1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbTelefone)
                    .addComponent(CampoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbcargo)
                    .addComponent(ComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InternaStatus)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(InternaEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefoneActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void ComboBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCargoActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
        // 
    }//GEN-LAST:event_BtEditarActionPerformed

    private void CampoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisarActionPerformed

    private void TabelaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaUsuariosMouseClicked
        int linha = TabelaUsuarios.getSelectedRow();
        if (linha == -1)
            return;
         new BuscarAdmController(this).usuarioSelecionado(linha);
    }//GEN-LAST:event_TabelaUsuariosMouseClicked

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void CampoInfoCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoInfoCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoInfoCargoActionPerformed
    public String GetIdUsuario(){
        return CampoInfoId.getText();
    }
    public String GetNome() {
        return CampoNome.getText();
    }

    public String GetEmail() {
        return CampoEmail.getText();
    }

    public String GetSenha() {
        return CampoSenha.getText();
    }

    public String GetTelefone() {
        return CampoTelefone.getText();
    }

    public String GetCargo() {
        return ComboBoxCargo.getSelectedItem().toString();
    }

    public javax.swing.JButton getBtSalvar() {
        return BtSalvar;
    }
    public javax.swing.JButton getBtExlcuir(){
        return BtExcluir;
    }
    public javax.swing.JButton getBtEditar(){
        return BtEditar;
    }
    
    public JProgressBar AtivarBarraProgresso() {
        return BarraProgresso;
    }

    public void RetornoDados(String nome, String email, String senha, String telefone, String cargo, String DataCadastro) {
        this.LbResultadoNome.setText(nome);
        this.LbResultadoEmail.setText(email);
        this.LbResultadoSenha.setText(senha);
        this.LbResultadoTelefone.setText(telefone);
        this.LbResultadoCargo.setText(cargo);
        this.LbResultadoData.setText(DataCadastro);
    }
    public void InfouUsuario(String Id, String nome, String email, String senha,String telefone, String cargo, String data, String DataAtualizacao){
        this.CampoInfoId.setText(Id);
        this.CampoInfoNome.setText(nome);
        this.CampoInfoEmail.setText(email);
        this.CampoInfoSenha.setText(senha);
        this.CampoInfoTelefone.setText(telefone);
        this.CampoInfoCargo.setText(cargo);
        this.CampoInfoDataCadastro.setText(data);
        this.CampoInfoDataAtualizacao.setText(DataAtualizacao);
    }
    public Map<String, String> InfouUsuarioComDados(){
    Map<String, String> dados = new HashMap<>();
    dados.put("id", CampoInfoId.getText());
    dados.put("nome", CampoInfoNome.getText());
    dados.put("email", CampoInfoEmail.getText());
    dados.put("senha", CampoInfoSenha.getText());
    dados.put("telefone", CampoInfoTelefone.getText());
    dados.put("cargo", CampoInfoCargo.getText());
    dados.put("dataCadastro", CampoInfoDataCadastro.getText());
    dados.put("dataAtualizacao", CampoInfoDataAtualizacao.getText());
    return dados;
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar BarraProgresso;
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoInfoCargo;
    private javax.swing.JTextField CampoInfoDataAtualizacao;
    private javax.swing.JTextField CampoInfoDataCadastro;
    private javax.swing.JTextField CampoInfoEmail;
    private javax.swing.JTextField CampoInfoId;
    private javax.swing.JTextField CampoInfoNome;
    private javax.swing.JTextField CampoInfoSenha;
    private javax.swing.JTextField CampoInfoTelefone;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoPesquisar;
    private javax.swing.JTextField CampoSenha;
    private javax.swing.JTextField CampoTelefone;
    private javax.swing.JComboBox<String> ComboBoxCargo;
    private javax.swing.JLabel IconPesquisar;
    private javax.swing.JInternalFrame InternaDadosPesquisa;
    private javax.swing.JInternalFrame InternaEditarUsuario;
    private javax.swing.JInternalFrame InternaStatus;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbEmail1;
    private javax.swing.JLabel LbInfoCargo;
    private javax.swing.JLabel LbInfoDataAtualizacao;
    private javax.swing.JLabel LbInfoDataCadastro;
    private javax.swing.JLabel LbInfoEmail;
    private javax.swing.JLabel LbInfoNome1;
    private javax.swing.JLabel LbInfoNome2;
    private javax.swing.JLabel LbInfoSenha;
    private javax.swing.JLabel LbInfotelefone;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbNome1;
    private javax.swing.JLabel LbResultado;
    private javax.swing.JLabel LbResultadoCargo;
    private javax.swing.JLabel LbResultadoData;
    private javax.swing.JLabel LbResultadoEmail;
    private javax.swing.JLabel LbResultadoNome;
    private javax.swing.JLabel LbResultadoSenha;
    private javax.swing.JLabel LbResultadoTelefone;
    private javax.swing.JLabel LbSenha;
    private javax.swing.JLabel LbSenha1;
    private javax.swing.JLabel LbTelefone;
    private javax.swing.JLabel LbTelefone1;
    private javax.swing.JLabel Lbcargo;
    private javax.swing.JLabel Lbcargo1;
    private javax.swing.JLabel Lbcargo2;
    private javax.swing.JTable TabelaUsuarios;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public JTextField getCampoPesquisar() {
        return CampoPesquisar;
    }

    public JTable getTabelaUsuarios() {
        return TabelaUsuarios;
    }
}
